### ISSUE TITLE
Antonym of assert

### ISSUE THREAD

**Issue by keithy** [jchook/phpunit-assert-throws#2]
Instead of assertNotThrows, how about disavowThrows ? 
Or at the very least, ensureDoesNotThrow

**Comment by jchook** [comment]
Yeah it bugs me too, but.. I think `assertNotThrows` best follows the PHPUnit naming conventions.

See the other odd built-in inverse assertions, for example:

- [`assertNotContains`](https://phpunit.readthedocs.io/en/8.0/assertions.html#assertcontains)
- [`assertNotCount`](https://phpunit.readthedocs.io/en/8.0/assertions.html#assertcount)
- [`assertNotSame`](https://phpunit.readthedocs.io/en/8.0/assertions.html#assertsame)
